export const en = {
  "title": "Khizhniak Anna - Portfolio",
  "name": "Khizhniak Anna",
  "portfolio": "Portfolio",
  "cv": "CV",
  "edu": "Education/Experience",
  "openProject": "Open project",
  "descProjectHobbyart": "flexbox, grid, jquery, java script, swippers, switcher, mobile view, animation",
  "descProjectHillel": "flexbox, jquery, swippers, switcher, mobile view, modal, regexp, form validation",
  "descProjectLocalize": "flexbox, mobile view, jquery",
  "descProjectMeliorit": "flexbox, jquery, swippers, mobile view",
  "descProjectBeauty": "flexbox, jquery, modal, mobile view",
  "descProjectFoxDigital": "flexbox, jquery, java script, swippers, switcher for 2 color schemes, mobile view",
  "descProjectFutureAcademy": "java script, flexbox, grid, bootstrap, swiper, tabs",
  "descProjectWPMeliorit": "wordpress, flexbox, jquery, swippers, mobile view",
  "reactUserListLabel": "(user list)",
  "reactPromoLabel": "(promo-code generator)",
  "reactExchangeLabel": "(currency exchange)",
  "experienceLabel": "Experience",
  "educationLabel": "Education",
  "personalData": "Personal data:",
  "personalName": "Full name:",
  "personalAge": "Age:",
  "years": "years",
  "personalCity": "City:",
  "city": "Odessa, Ukraine (I live temporarily in Bucharest, Romania)",
  "ukr": "(Ukraine),",
  "rom": "(Romania)",
  "personalPhone": "Phone:",
  "personalMessenger": "Messenger:",
  "summary": "Summary:",
  "summaryAbout": "I'm intern/junior Front-end developer with experience in HTML,\n" +
    "CSS/SASS/SCSS, JavaScript, React, Redux. I'm looking for interesting job and\n" +
    "want to learn more due to practice, grow and multiply my knowledge.\n" +
    "I also want to get experience working in a real project.",
  "github": "GitHub repositories",
  "mainPage": "Go to main page",
  "experienceRelated": "Experience (related to position):",
  "experienceText": "I have been graduated from internship (10.10.2023). " +
    "The internship included: work with PUG, React, adaptive layout, mentor support. " +
    "Finished tasks you can see in my ",
  "githubLink": "GitHub repository",
  "experienceText2": "My experience in IT mostly are pet-projects. You can check them on page ",
  "experienceNotRelated": "Experience (does not apply to position):",
  "experienceManager": " - Online store",
  "experienceManagerPosition": "Position: content manager (part-time, remotely)",
  "experienceManagerResp": "Responsibilities: add/edit/remove products on web-site, add product description, communication \n" +
    "with suppliers.",
  "experienceManager2": " - Online store",
  "experienceManager2Position": "Position: manager, content manager, copywriter",
  "experienceManager2Resp": "Responsibilities: add/edit/remove products on web-site, add product description, communication\n" +
    "with suppliers, mailing (with Mailchimp, Sendpulse), work with clients (consulting, selling, orders,\n" +
    "delivery control, resolve conflicts).",
  "experienceOperator": " - \"Intertelecom\"",
  "experienceOperatorPosition": "Position: Information support center operator, online technical support chat operator",
  "experienceOperatorResp": "Responsibilities: consulting clients, interacting with other company departments for resolving client issues, selling company services. ",
  "techSkills": "Tech skills:",
  "typescript": "(study since November 2023)",
  "node": "(study since January 2024)",
  "basic": "(basic knowledge)",
  "softSkills": "Soft skills:",
  "adaptivity": "Adaptivity",
  "communication": "Communication",
  "timeManagement": "Time management",
  "teamWork": "Teamwork skills",
  "problemSolving": "Problem-solving",
  "hillelPro": " - Hillel “Front-end Pro” course (Java Script, React)",
  "hillelBasic": " - Hillel “Front-end Basic” course",
  "university": " - Odessa State Environmental University.",
  "universitySpecialty": "Specialty: computer systems engineer.",
  "college": "- College of Industrial Automation ONAFT (Technical School of Industrial Automation OSAR).",
  "collegeSpecialty": "Specialty: programmer for automated systems and EOM.",
  "language": "Knowledge of languages:",
  "ukrainianLang": "Ukrainian (native)",
  "russianLang": "Russian (native)",
  "englishLang": "English (intermediate)",
  "viewDetails": "View details"
}



