export const ru = {
  "title": "Хижняк Анна - Портфолио",
  "name": "Хижняк Анна",
  "portfolio": "Портфолио",
  "cv": "Резюме",
  "edu": "Образование/Опыт",
  "openProject": "Открыть сайт",
  "descProjectHobbyart": "флексбокс, грид, jquery, java script, слайдер, переключатель, анимация, адаптивный дизайн",
  "descProjectHillel": "флексбокс, грид, jquery, java script, слайдер, переключатель, адаптивный дизайн, regexp, валидация форм",
  "descProjectLocalize": "флексбокс, адаптивный дизайн, jquery",
  "descProjectMeliorit": "флексбокс, jquery, слайдер, адаптивный дизайн",
  "descProjectBeauty": "флексбокс, jquery, модальное окно, адаптивный дизайн",
  "descProjectFoxDigital": "флексбокс, jquery, java script, слайдер, переключатель цветовой схемы, адаптивный дизайн",
  "descProjectFutureAcademy": "флексбокс, грид, java script, bootstrap, слайдер, табы",
  "descProjectWPMeliorit": "wordpress, флексбокс, jquery, слайдер, адаптивный дизайн",
  "descProjecReactUsers": "java script, React, Redux, Rest API",
  "reactUserListLabel": "(список пользователей)",
  "reactPromoLabel": "(генератор промо-кодов)",
  "reactExchangeLabel": "(обмен валют)",
  "experienceLabel": "Опыт",
  "educationLabel": "Образование",
  "personalData": "Личные данные:",
  "personalName": "Полное имя:",
  "personalAge": "Возраст:",
  "years": "года",
  "personalCity": "Город:",
  "city": "Одесса, Украина (на данный момент, временно, живу в Бухаресте, Румыния)",
  "ukr": "(Украина),",
  "rom": "(Румыния)",
  "personalPhone": "Телефон:",
  "personalMessenger": "Мессенджер:",
  "summary": "О себе:",
  "summaryAbout": "Я intern/junior Front-end разработчик. Имею опыт работы с HTML,\n" +
    "CSS/SASS/SCSS, JavaScript, React, Redux. На данный момент не имею коммерческого опыта, \n" +
    "но постоянно практикуюсь, улучшаю свои навыки и учусь. Хочу поработать на реальном проекте,\n" +
    "чтобы полностью погрузиться в web-разработку, приумножить свои знания и отрабатывать их на практике.\n",
  "github": "GitHub репозитории",
  "mainPage": "Перейти на главную",
  "experienceRelated": "Опыт (связанный с должностью):",
  "experienceText": "Я прошла стажировку (10.10.2023). " +
    "Стажировка включала в себя: работу с PUG, React, адаптивную верстку, сопровождение ментора. " +
    "Отработанные задания и исходный код можно посмотреть в моем ",
  "githubLink": "GitHub репозитории",
  "experienceText2": "Мой опыт в IT, в основном, пет-проекты. Каждый из них можно посмотреть в моем ",
  "experienceNotRelated": "Опыт (не связанный с должностью):",
  "experienceManager": " - Интернет-магазин",
  "experienceManagerPosition": "Должность: контент-менеджер (удаленно, частичная занятость)",
  "experienceManagerResp": "Обязанности: добавление/редактирование/удаление товаров на сайте, описание товаров, взаимодействие с поставщиками. ",
  "experienceManager2": " - Интернет-магазин",
  "experienceManager2Position": "Должность: менеджер, копирайтер, контент-менеджер",
  "experienceManager2Resp": "Обязанности: добавление/редактирование/удаление товаров на сайте, описание товаров, взаимодействие с поставщиками. " +
    "E-mail рассылки (Maichimp, Sendpulse), работа с клиентами (консультация, продажи, ведение заказов, контроль доставки, " +
    "решение конфликтных ситуаций). ",
  "experienceOperator": " - \"Интертелеком\"",
  "experienceOperatorPosition": "Должность: оператор центра информационной поддержки (в голосовом режиме и онлайн-чат) ",
  "experienceOperatorResp": "Обязанности: консультация клиентов, взаимодействие с другими отделами компании в решении вопросов клиентов, продажа услуг компании. ",
  "techSkills": "Технические навыки:",
  "typescript": "(обучаюсь с ноября 2023)",
  "basic": "(базовые знания)",
  "softSkills": "Софт скилы:",
  "adaptivity": "Адаптивность",
  "communication": "Общительность",
  "timeManagement": "Навыки тайм-менеджмента",
  "teamWork": "Работа в команде",
  "problemSolving": "Решение проблем",
  "hillelPro": " - Курс от Hillel “Front-end Pro” (Java Script, React)",
  "hillelBasic": " - Курс от Hillel “Front-end Basic” (HTML, CSS)",
  "university": " - Одесский государственный экологический университет.",
  "universitySpecialty": "Специальность: инженер компьютерных систем.",
  "college": " - Техникум промышленной автоматики ОНАПТ (Техникум промышленной автоматики ОГАХ).",
  "collegeSpecialty": "Специальность: программист для автоматизированных систем и ЭОМ.",
  "language": "Знание языков:",
  "ukrainianLang": "Украинский (родной)",
  "russianLang": "Русский (отлично)",
  "englishLang": "Английский (intermediate)",
  "node": "(изучаю с января 2024)",
  "viewDetails": "Подробности"
}