export const uk = {
  "title": "Хiжняк Анна - Портфолiо",
  "name": "Хiжняк Анна",
  "portfolio": "Портфолiо",
  "cv": "Резюме",
  "edu": "Освіта/Досвід",
  "openProject": "Відкрити сайт",
  "descProjectHobbyart": "флексбокс, грід, jquery, java script, слайдер, перемикач, анімація, адаптивний дизайн",
  "descProjectHillel": "флексбокс, грід, jquery, java script, слайдер, перемикач, адаптивний дизайн, regexp, валідація форм",
  "descProjectLocalize": "флексбокс, адаптивний дизайн, jquery",
  "descProjectMeliorit": "флексбокс, jquery, слайдер, адаптивний дизайн",
  "descProjectBeauty": "флексбокс, jquery, модальне вікно, адаптивний дизайн",
  "descProjectFoxDigital": "флексбокс, jquery, java script, слайдер, перемикач кольору сайту, адаптивний дизайн",
  "descProjectFutureAcademy": "флексбокс, грід, java script, bootstrap, слайдер, таби",
  "descProjectWPMeliorit": "wordpress, флексбокс, jquery, слайдер, адаптивний дизайн",
  "descProjecReactUsers": "java script, React, Redux, Rest API",
  "reactUserListLabel": "(список користувачів)",
  "reactPromoLabel": "(генератор промо-кодів)",
  "reactExchangeLabel": "(обмін валют)",
  "experienceLabel": "Досвід",
  "educationLabel": "Освіта",
  "personalData": "Особисті дані:",
  "personalName": "Повне ім'я:",
  "personalAge": "Вік:",
  "years": "роки",
  "personalCity": "Місто:",
  "city": "Одеса, Україна (на даний момент, тимчасово, проживаю в Бухаресті, Румунія)",
  "ukr": "(Україна),",
  "rom": "(Румунія)",
  "personalPhone": "Телефон:",
  "personalMessenger": "Мессенджер:",
  "summary": "Про себе:",
  "summaryAbout": "Я intern/junior Front-end розробник. Маю досвід роботи з HTML,\n" +
    "CSS/SASS/SCSS, JavaScript, React, Redux. На даний момент не маю комерційного досвіду, \n" +
    "але постійно практикуюсь, покращую свої навички та продовжую вчитися. Хочу працювати на реальному проєкті,\n" +
    "щоб повністю поринути у web-розробку, примножувати свої знання та відпрацьовувати їх на практиці.\n",
  "github": "GitHub репозиторії",
  "mainPage": "Перейти на головну",
  "experienceRelated": "Досвід (пов'язаний з посадою):",
  "experienceText": "Я пройшла стажування (10.10.2023). " +
    "На стажуванні працювала з PUG, React, адаптивною версткою. Процес супроводжувався підтримкою ментора. " +
    "Виконані завдання та вихідний код можна передивитись в моєму  ",
  "githubLink": "GitHub репозиторії",
  "experienceText2": "Мій досвід в IT, переважно, пет-проєкти. Кожен з них можна подивитись в моєму ",
  "experienceNotRelated": "Досвід (не пов'язаний з посадою):",
  "experienceManager": " - Інтернет-магазин",
  "experienceManagerPosition": "Посада: контент-менеджер (віддалено, часткова зайнятість)",
  "experienceManagerResp": "Обов'язки: додавання/редагування/видалення товарів на сайті, опис товарів, взаємодія з постачальниками. ",
  "experienceManager2": " - Інтернет-магазин",
  "experienceManager2Position": "Посада: менеджер, копірайтер, контент-менеджер",
  "experienceManager2Resp": "Обов'язки: додавання/редагування/видалення товарів на сайті, опис товарів, взаємодія з постачальниками. " +
    "E-mail розсилки (Maichimp, Sendpulse), робота з клієнтами (консультація, продаж, ведення замовлень, контроль доставки, " +
    "вирішення конфліктних ситуацій). ",
  "experienceOperator": " - \"Інтертелеком\"",
  "experienceOperatorPosition": "Посада: Оператор центру інформаційної підтримки (в голосовому режимі та онлайн-чат)",
  "experienceOperatorResp": "Обов'язки: консультація клієнтів, взаємодія з іншими відділами компанії для вирішення питань клієнтів, продаж послуг компанії.",
  "techSkills": "Технічні навички:",
  "typescript": "(навчаюсь з листопада 2023)",
  "basic": "(базові знання)",
  "softSkills": "Софт скіли:",
  "adaptivity": "Адаптивність",
  "communication": "Комунікабельність",
  "timeManagement": "Навички тайм-менеджменту",
  "teamWork": "Робота в команді",
  "problemSolving": "Вирішення проблем",
  "hillelPro": " - Курс від Hillel “Front-end Pro” (Java Script, React)",
  "hillelBasic": " - Курс від Hillel “Front-end Basic” (HTML, CSS)",
  "university": " - Одеський державний екологічний университет.",
  "universitySpecialty": "Спеціальність: інженер комп'ютерних систем.",
  "college": "- Технікум промислової автоматики ОНАХТ. (Технікум промислової автоматики ОДАХ).",
  "collegeSpecialty": "Спеціальність: програміст для автоматизованых систем та ЕОМ.",
  "language": "Знання мов:",
  "ukrainianLang": "Українська (рідна)",
  "russianLang": "Російська (відмінно)",
  "englishLang": "Английска (intermediate)",
  "node": "(вивчаю з сiчня 2024)",
}